### ISSUE TITLE
Kobold deals 1010 damage

### ISSUE THREAD

**Issue by thisjustin816** [NesHacker/LabyrinthOfTheDragon#61]
After beating the owlbear, I encountered a two monster encounter. The first one was a zombie and the second a kobold. The kobold did 1010 damage and killed me.

**Comment by grendell** [comment]
I also had this exact situation happen and took 1299 damage from the Kobold. I was also poisoned by the zombie, in case that is relevant.

**Comment by rsandor** [comment]
Holy cow, okay yeah that is a *serious* issue. I'll look into after have my ☕

**Comment by thisjustin816** [comment]
Also, is it supposed to persist the character level after you die? If so, any plans for a save function? If not I can create a new issue.

**Comment by rsandor** [comment]
@thisjustin816 - Yeah, you keep your level and items when you die. This makes it have a more rogue-like feel where you can get further and further as you learn what works / doesn't and power up.

Sorry! A lot of this stuff is just part of my head canon and isn't clearly explained the way the game is programmed right now!

**Comment by rsandor** [comment]
@grendell & @thisjustin816 - Was this while you were still on floor 2, or did you go down to floor 3?

**Comment by rsandor** [comment]
Never mind, it's caused by a missing null terminator 🤦

**Comment by rsandor** [comment]
Fixed in the latest release!

**Comment by PowerPaladin** [comment]
This issue is still present in 1.0.5. Floor 3 or 4. Exact same encounter as the other posters: Defeated the Owlbear, then encountered a Zombie + Kobold combo. Zombie poisoned me (I remedied), and then Kobold hit for ~2900 damage.

**Comment by grendell** [comment]
Sounds like it might be the same issue as https://github.com/NesHacker/LabyrinthOfTheDragon/issues/78, which should be fixed by https://github.com/NesHacker/LabyrinthOfTheDragon/pull/79, pending a merge.
